# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2db7bc92a00b67e45ebaf3d395e573d696afbd7df4ec5f5734ad26e9ac453eb3ff4a63583599cad5d5a920e9ceae6a2b60847979e9aead9d84f6fd18fe6c94b1

test:
  secret_key_base: 645b56f13405dff6f9cbfd3f01ce65a87b001b861919fc7fdbf1e9767279470dbba53fe868d2c9ac17bab456de945732d199de3a4ce8eb2e667c9b7b1d7fb616

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
